$(document).ready(function() {
	var audioObject = null;

	/*
	 *  Spotify assigns a unique id to each artist in its database.
	 *  This function searches for an artist's name and returns the
	 *  Id. Spotify will not allow you to get an artist's top tracks
	 *  by thier name, only their id.
	 */
	function getArtistId(query) {
		var id = "";

		var request = {
			query: query,
			type: 'artist'
		};

		var result = $.ajax({
			url: "https://api.spotify.com/v1/search",
			data: request,
			dataType: 'json',
			type: 'GET',
		}).done(function(result) {
			if(result.artists.items.length === 0) {
				showError("No results found for " + query);
			} else {
				id = result.artists.items[0].id;
				getTopTracks(id);
			}
		}).fail(function() {
			alert("Error getting artist.");
		});
		return id;
	}


	/*
     *  Given an artit's unique Spotify id, get the top tracks for
     *  that artist.
	 */
	function getTopTracks(artistId) {
		var request = {
			country: "US"
		};

		var result = $.ajax({
			url: "https://api.spotify.com/v1/artists/" + artistId + "/top-tracks",
			data: request,
			dataType: "json",
			type: "GET"
		}).done(function(result) {
			showResults(result);
			return result;
		}).fail(function() {
			alert("Error getting tracks.");
		});
	}

	// Clear the results of any previous searches on the page
	function clearResults() {
		$('#results').html("");
		$('#results').addClass('hidden');
	}

	// Show any errors in the results tab
	function showError(errorText) {
		clearResults();
		$('#results').removeClass('hidden');
		$('#results').append('<h2>' + errorText + '</h2>');
	}

	// Display the results of a search
	function showResults(results) {
		/*
		 *  Generate a <ul> containing the search results, including
		 *  relevent data, play/pause buttons for each track and
		 *  links to appropriate spotify pages
		 */
		for (var i = 0; i <= 2; i++) {	
			$('#results').append('<div class="track">' +
				'<button class="btn-play play" data-preview="' + results.tracks[i].preview_url + '"></button>' +
				'<div class="track-info">' +
					'<a href="' + results.tracks[i].external_urls.spotify + '" target="_blank" class="spotify-link">' +
						'<p>' + results.tracks[i].name + ' - </p>' +
						'<p>' + results.tracks[i].artists[0].name + '</p>' +
					'</a>' +
					'<p class="track-album-title">' + results.tracks[i].album.name + '</p>' +
				'</div>' +
				'<a href="' + results.tracks[i].album.external_urls.spotify + '" target="_blank">' +
					'<img class="track-album-art" src="' + results.tracks[i].album.images[2].url + '">' +
				'</a>' +
			'</div>');

		};

		// Display the #results element
		$('#results').removeClass('hidden');

		/*
		 *  Define functionality for the play/pause buttons
		 *  generated by this function.
		 */
		$('.btn-play').click(function(event) {
			event.preventDefault();

			if ($(this).hasClass('pause')){
				audioObject.pause();
				$(this).removeClass('pause');
				$(this).addClass('play');
			} else if ($(this).hasClass('play')) {
				audioObject = new Audio($(this).attr('data-preview'));
				audioObject.play();
				$(this).removeClass('play');
				$(this).addClass('pause');
			}
		});
	}

	// Define functionality for the search button
	$('#btn-search').click(function(event) {
		event.preventDefault();

		clearResults();

		var searchQuery = $('#search-query').val();
		getArtistId(searchQuery);
	});

	// Clear the search bar text when clicked
	$('#search-query').click(function(event) {
		$(this).val("");
	});
});